language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - ${HOME}/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  slack:
    secure: kD6V9YYVi7ZKqttpcMG17qzkgs4wnML7c/3uI5bu9ktBgUNJZNyMFvfZ6QCeBhOzkPBfoEmqHSKCjpyCKgQwG6gM07Ml9isN9z2Otcg5WPno3+2HmRLWLJ5aPYjKD+/8U0FAQ1x/OgHhdZojbbqKxhZGhALsjJbFEfQXH4C9C4xnx2DOaonbtWY6KTaVBF6VyAF7jdVQSp9QLXca+XfjNd+v56nVVoRwatxW1FaLp0IcNNH/CXHqOtDo8dshkwi1Xj+wc6SWJ1g0jxnugaDS5CHppe+qfyVHdb9Bt/MRVlVnbh0ZRSIHYBKjmyt+dEn1eTLT4f44mkWiNpfAGUllk1VfV8MHVXNgkhMNm+AMGJhQKjPCszhPf38esXCt58AK5zlWE2WOkKLMLb0afSmLgm/AqKpR/vNeNAEqg1rP4HgElJSr59WbbctvNQWfmDOo8ofW3Og1PKr3l3iIO17QWqtfS606BtTlOwG8eyRY89dOs4irn1KRSDrP8hbE6GybK+eu1QAEPFZ7Uv7XmYcynEBcFwDlhl5jirfs7q9wi629oupfY/JA7PQEaFXGMDqe9N68dAhxH/qKz0gcjizwVzllDoS5AT67ySySABa1b7MimigrU5qmMMnYwGiOSs0aLLU+WOzpug9nmkYxvgt7IluXudAOAP684CPfmmuEnKk=
